spring:
  profiles:
    active: local
---
server:
  port: 8081
spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-event-group
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:library
    data-username: sa
    data-password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  h2:
    console:
      enabled: true